spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    service-user: 
      path: /service/**
      serviceId: service-user

spring:
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: E:/upload/temp/
      max-file-size: 1024MB
      max-request-size: 1024MB

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 30000 
    
logging:
  level:
    org: DEBUG    
    