spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hjjj/scconfig
          username: 819748949@qq.com
          password: hu2455055524
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,bus-refresh
  endpoint:
    health:
      show-details: always 
      
      
      