spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://192.168.0.50:3306/test?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      initial-size: 1
      max-active: 5
      min-idle: 1
      max-wait: 2
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response: 
      enabled: true
    
    
    